# Snyk demo pipeline

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'timsnyk'
    testType: 'app'
    monitorWhen: 'never'
    failOnIssues: true
    projectName: 'python-azure'