trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'timsnyk'
    testType: 'app'
    failOnIssues: false
    monitorWhen: 'never'